[package]
name = "lifx"
version = "0.2.0"
authors = ["Andrew Chin <achin@eminence32.net>"]
description = "Utilities for controlling your LIFX bulbs"

[workspace]
members = ["lifx-core", "examples/multizone_test", "examples/waveform_test", "utils/get_all_info"]

[lib]

[dependencies]
