[package]
name = "lifx"
version = "0.1.0"
authors = ["Andrew Chin <achin@eminence32.net>"]
description = "Library for controlling your LIFX light bulbs"


[dependencies]
byteorder = "0.4"
rand = "0.3"
libc = "0.2"
chrono = "0.2"
hsl = "0.1"
term = "0.2"

